### ISSUE TITLE
Hard to debug config file loading

### ISSUE THREAD

**Issue by boblsc** [XENONnT/appletree#70] opened 2022-12-14 02:54 UTC
When loading the config file, sometimes it loads NoneType and it's hard to know which file failed. 
``File` ~/appletree/appletree/utils.py:88, in load_json(file_name)
     85 @export
     86 def load_json(file_name: str):
     87     """Load data from json file."""
---> 88     with open(get_file_path(file_name), 'r') as file:
     89         data = json.load(file)
     90     return data

TypeError: expected str, bytes or os.PathLike object, not NoneType
``

My temporary fix is to make it print all names in
`@export
class Map(Config):
    """Map is a special config which takes input file"""

    def build(self):
        """Cache the map to jnp.array"""

        
        if self.name in _cached_configs:
            print('want to get:',self.name)
            file_path = _cached_configs[self.name]
            
        else:
            file_path = get_file_path(self.get_default())
            _cached_configs.update({self.name: file_path})
`
But there might be better ways to print what didn't load.

**Comment by boblsc** [comment] 2022-12-15 19:31
No, it's not showing.
`/home/scli/appletree/appletree/utils.py:157: UserWarning: Using the private repo to load s1_xyz_sr0.json locally
  warn(f'Using the private repo to load {fname} locally')` 
Something with the Python version maybe

**Comment by dachengx** [comment] 2022-12-16 06:42
I think we'd better change all `warn` to print, to avoid this complex mechanism.

**Comment by dachengx** [comment] 2022-12-18 18:06
@boblsc I guess maybe the issue is solved in https://github.com/XENONnT/appletree/pull/73. Would you try if now the master branch works well? Sorry I was about to ask for your review but forgot to do that in the PR...

**Comment by xzh19980906** [comment] 2023-06-21 18:45
I think we can close this issue

**Closed by xzh19980906** 2023-06-21 18:45 UTC
Labels: good first issue
